### ISSUE TITLE
【bug反馈】

### ISSUE THREAD

**Issue by BrazilAmando** [hx24/js-minimap#1]
大神太牛了！找了好久，这应该是全网唯一一个实现网页导航功能的JS库，已完美运行，不过过程中有几处bug，建议大神完善一下
bug:报改变常量i值错误
采取措施：将const i更改为 let i错误消失，运行正常。
参考截图
![image](https://github.com/hx24/js-minimap/assets/125205627/07f49102-54e3-49f2-9f13-c102f20d0fa4)

**Comment by hx24** [comment]
没能复现问题，但是看起来是依赖的一个库导致的，已更新
